version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npx nodemon index.js
    volumes:
      - ./react_app:/react_app

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:3000
    command: npm start
    volumes:
      - ./react_app:/react_app

