---
version: "3.8"
services:
  backend:
    container_name: backend
    image: myapp
    ports:
      - 3000:3000
    command: npx nodemon index.js
    volumes:
      - ./MyApp:/MyApp
  frontend:
    container_name: frontend
    image: myapp
    ports:
      - 443:3000
    command: npm start
    volumes:
      - ./MyApp:/MyApp

